[default]
address = "127.0.0.1"
port = 4443
workers = 16
max_blocking = 512
keep_alive = 5
ident = "Rocket"
ip_header = "X-Real-IP" # set to `false` to disable
proxy_proto_header = false # set to `false` (the default) to disable
log_level = "normal"
temp_dir = "/tmp"
cli_colors = true
secret_key = "WZ7svtcM0bI1zWmUoSViNK9EcUMf239q0UH9MHJ3RmM="

[default.limits]
form = "64 kB"
json = "1 MiB"

[default.tls]
certs = ".cert/api.jelomu.local.crt"
key = ".cert/api.jelomu.local.key"

[default.shutdown]
ctrlc = true
signals = ["term", "hup"]
grace = 5
mercy = 5

