- name: Deploy kafka
  hosts: localhost
  collections:
    - ansible.posix
    - containers.podman
  tasks:
    - name: Dependencies podman - Check if required
      ansible.builtin.shell:
        cmd: podman --version
      register: podman_version
      # stdout version string changed
      changed_when: "'podman version 4.9.3' not in podman_version.stdout"
    # Ready Networking
    - name: Dependencies podman - Create Kafka network
      containers.podman.podman_network:
        name: kafka-net
        state: present
#            # Ready storage
#            - name: Create Kafka volume for data persistence
#              community.podman.podman_volume:
#                name: kafka-data
#                state: present
#            # Obtain image
#            - name: Pull the Apache Kafka image
#              community.podman.podman_image:
#                name: docker.io/bitnami/kafka:latest
#                source: pull
#            - name: Pull the Apache Sookeper image
#              community.podman.podman_image:
#                name: docker.io/bitnami/zookeeper:latest
#                source: pull
#
#            - name: Deploy Zookeeper container (Optional, but usually required)
#              community.podman.podman_container:
#                name: zookeeper
#                image: docker.io/bitnami/zookeeper:latest
#                ports:
#                  - "2181:2181"
#                networks:
#                  - name: kafka-net
#                env:
#                  ALLOW_ANONYMOUS_LOGIN: "yes"
#                state: started
#                recreate: true
#            - name: Deploy Apache Kafka container
#              community.podman.podman_container:
#               name: kafka
#                image: docker.io/bitnami/kafka:latest
#                ports:
#                  - "9092:9092"
#                  - "2181:2181" #Zookeeper port
#                volumes:
#                  - "kafka-data:/bitnami/kafka"
#                networks:
#                  - name: kafka-net
#                env:
#                  KAFKA_CFG_NODE_ID: 0
#                  KAFKA_CFG_PROCESS_ROLES: controller,broker
#                  KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:29092
#                  KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://{{ ansible_host }}:9092
#                  KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
#                  KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 0@{{ ansible_host }}:29092
#                  KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
#                  KAFKA_CFG_ZOOKEEPER_CONNECT: "{{ ansible_host }}:2181" #Or the zookeeper container name if you use a seperate zookeeper.
#                  ALLOW_PLAINTEXT_LISTENER: "yes" # For development only, remove for production!
#                state: started
#                recreate: true
#
#            - name: Check Kafka container status
#              community.podman.podman_container:
#                name: kafka
#                register: kafka_status
#
#            - name: Display Kafka container status
#              debug:
#                var: kafka_status.state
#